# -*- coding: utf-8 -*-
"""Gemeenten waarvoor Den Dekker Dakbedekking een eigen pagina heeft."""

# slug bij Den Dekker (dakwerken-<slug>), naam, provincie, streek, deelkernen, profiel
GEMEENTEN = [
    ("antwerpen", "Antwerpen", "Antwerpen", "Stad Antwerpen",
     "Antwerpen, Berchem, Borgerhout, Deurne, Ekeren, Hoboken, Merksem, Wilrijk en Berendrecht-Zandvliet-Lillo",
     "Het woningbestand in de stad bestaat grotendeels uit gesloten rijbebouwing. Aan de straatzijde ligt meestal een hellend pannendak, achteraan een plat dak boven de aanbouw. Op de scheiding tussen die twee constructies en langs de gemene muren zitten de meeste lekken."),
    ("brasschaat", "Brasschaat", "Antwerpen", "Antwerpse rand",
     "Brasschaat en Maria-ter-Heide",
     "Brasschaat telt veel open bebouwing op ruime percelen, met villa's uit het interbellum en bungalows uit de jaren zestig en zeventig. Overhangende bomen zorgen voor blad in de goten en mos op de noordzijde van het dakvlak."),
    ("schoten", "Schoten", "Antwerpen", "Antwerpse rand",
     "Schoten, Deuzeld en Koningshof",
     "Schoten combineert vooroorlogse kernbebouwing met naoorlogse verkavelingen. In de wijken langs het Albertkanaal staan veel halfopen woningen met een zadeldak en een platte uitbouw achteraan."),
    ("kapellen", "Kapellen", "Antwerpen", "Antwerpse rand",
     "Kapellen, Hoogboom en Putte-Kapellen",
     "Kapellen heeft een groot aandeel vrijstaande woningen met een steil hellend dak. Bij woningen van voor 1980 ontbreekt dakisolatie vaak volledig of zit ze alleen tussen de kepers zonder onderdak."),
    ("stabroek", "Stabroek", "Antwerpen", "Antwerpse Polder",
     "Stabroek, Hoevenen en Putte",
     "Stabroek ligt in de polder, dicht bij de haven. De open ligging betekent een hoge windbelasting op nokvorsten, gevelpannen en dakranden, zeker bij westenwind."),
    ("kalmthout", "Kalmthout", "Antwerpen", "Noorderkempen",
     "Kalmthout, Heide, Nieuwmoer en Achterbroek",
     "Rond de Kalmthoutse Heide staan veel vrijstaande woningen tussen naaldbomen. Dennennaalden verstoppen goten en bladvangers sneller dan blad, en zorgen op pannendaken voor vochtophoping."),
    ("essen", "Essen", "Antwerpen", "Noorderkempen",
     "Essen-Centrum, Wildert, Horendonk, Hoek en Statie",
     "Essen grenst aan Nederland en heeft een gespreide bebouwing met veel losse hoeves en landelijke woningen. Op oude bijgebouwen ligt vaak nog asbestcement in golfplaatvorm."),
    ("wuustwezel", "Wuustwezel", "Antwerpen", "Noorderkempen",
     "Wuustwezel, Loenhout en Gooreind",
     "Wuustwezel is een landbouwgemeente met veel losstaande stallen en loodsen. Bij die gebouwen speelt de vraag naar vervanging van asbesthoudende golfplaten sterker dan bij de woningen zelf."),
    ("brecht", "Brecht", "Antwerpen", "Noorderkempen",
     "Brecht, Sint-Job-in-'t-Goor en Sint-Lenaarts",
     "Brecht bestaat uit drie kernen met elk een eigen bouwperiode. In Sint-Job-in-'t-Goor staan veel woningen uit de jaren zeventig en tachtig, waarvan de eerste generatie dakbedekking nu aan vervanging toe is."),
    ("rijkevorsel", "Rijkevorsel", "Antwerpen", "Noorderkempen",
     "Rijkevorsel en Sint-Jozef",
     "Rijkevorsel heeft een kern met gesloten bebouwing en daarbuiten verkavelingen met halfopen woningen. Steenbakkerijverleden betekent veel gemetselde schouwen die na dertig tot veertig jaar hervoegd moeten worden."),
    ("hoogstraten", "Hoogstraten", "Antwerpen", "Noorderkempen",
     "Hoogstraten, Meer, Meerle, Minderhout, Wortel en Meersel-Dreef",
     "Hoogstraten telt naast woningen veel serres en landbouwloodsen. De Kolonie van Wortel staat sinds 2021 op de Werelderfgoedlijst van UNESCO, wat betekent dat dakwerken daar onder erfgoedregels vallen."),
    ("merksplas", "Merksplas", "Antwerpen", "Noorderkempen",
     "Merksplas en Merksplas-Kolonie",
     "De Kolonie van Merksplas staat sinds 2021 op de Werelderfgoedlijst van UNESCO. Voor gebouwen in en rond dat gebied gelden bijkomende voorwaarden bij het vervangen van dakbedekking."),
    ("turnhout", "Turnhout", "Antwerpen", "Kempen",
     "Turnhout, Zevendonck en Schorvoort",
     "Turnhout is de grootste stad van de Kempen. Het centrum bestaat uit gesloten bebouwing met hellende daken vooraan en platte daken op de achterbouw; de randwijken tellen veel woningen uit de jaren zestig en zeventig."),
    ("vosselaar", "Vosselaar", "Antwerpen", "Kempen",
     "Vosselaar",
     "Vosselaar is een compacte gemeente naast Turnhout met veel open en halfopen woningen op ruime percelen tussen dennenbos. Naaldafval in de goot is er een terugkerend onderhoudspunt."),
    ("beerse", "Beerse", "Antwerpen", "Kempen",
     "Beerse en Vlimmeren",
     "Beerse heeft een lange steenbakkerijtraditie. Veel woningen dragen keramische pannen van lokale makelij, waarvan de modellen bij deelvervanging soms niet meer leverbaar zijn."),
    ("lille", "Lille", "Antwerpen", "Kempen",
     "Lille, Gierle, Poederlee en Wechelderzande",
     "Lille bestaat uit vier landelijke kernen met veel vrijstaande woningen en langgevelhoeves. Bij die hoeves loopt het dakvlak ver door, wat het risico op mosgroei en verzakte nokvorsten vergroot."),
    ("kasterlee", "Kasterlee", "Antwerpen", "Kempen",
     "Kasterlee, Lichtaart en Tielen",
     "Kasterlee ligt in een bosrijk gebied. Vakantiewoningen en tweede verblijven staan er vaak lange tijd leeg, waardoor een lekkage pas laat wordt opgemerkt."),
    ("herentals", "Herentals", "Antwerpen", "Kempen",
     "Herentals, Noorderwijk en Morkhoven",
     "Herentals heeft een historische kern met beschermde panden en daarbuiten veel naoorlogse rijwoningen. Voor panden in de vastgestelde inventaris van het bouwkundig erfgoed gelden aparte regels bij dakwerken."),
    ("geel", "Geel", "Antwerpen", "Kempen",
     "Geel, Punt, Bel, Larum, Winkelomheide, Stelen, Zammel, Oosterlo en Ten Aard",
     "Geel is qua oppervlakte een van de grootste gemeenten van de provincie, met een groot aantal gehuchten. De bebouwing is er sterk gespreid, met veel vrijstaande woningen uit de jaren zestig tot tachtig."),
    ("mol", "Mol", "Antwerpen", "Kempen",
     "Mol-Centrum, Achterbos, Donk, Ezaart, Ginderbuiten, Gompel, Millegem, Rauw, Sluis en Wezel",
     "Mol telt een tiental gehuchten en veel bebouwing tussen zandwinningsplassen en bos. Vakantiewoningen rond het Zilvermeer hebben vaak een plat dak met een oude bitumineuze afdichting."),
    ("dessel", "Dessel", "Antwerpen", "Kempen",
     "Dessel en Witgoor",
     "Dessel is een kleine gemeente tussen kanalen en zandgroeves. De open ligging maakt daken gevoelig voor windbelasting op de nok en de gevelpannen."),
    ("retie", "Retie", "Antwerpen", "Kempen",
     "Retie en Schoonbroek",
     "Retie heeft veel landelijke bebouwing met ruime dakvlakken. Bij oudere woningen ligt de dakbedekking nog rechtstreeks op de kepers zonder onderdakfolie."),
    ("arendonk", "Arendonk", "Antwerpen", "Kempen",
     "Arendonk en Voorheide",
     "Arendonk grenst aan Nederland. In de kern staan sigarenmakerswoningen uit de negentiende eeuw, met steile pannendaken en gemetselde schouwen die regelmatig onderhoud vragen."),
    ("ravels", "Ravels", "Antwerpen", "Kempen",
     "Ravels, Weelde en Poppel",
     "Ravels bestaat uit drie kernen tegen de Nederlandse grens. De bebouwing is landelijk en open, met veel bijgebouwen waarop nog asbestcement ligt."),
    ("meerhout", "Meerhout", "Antwerpen", "Kempen",
     "Meerhout en Gestel",
     "Meerhout ligt in de vallei van de Grote Nete. Woningen in de laagste delen hebben meer last van vocht, wat de gevolgen van een daklek sneller zichtbaar maakt in het metselwerk."),
    ("balen", "Balen", "Antwerpen", "Kempen",
     "Balen, Olmen, Schoor en Hulsen",
     "Balen heeft een industrieel verleden en veel arbeiderswoningen uit de eerste helft van de twintigste eeuw. Op die woningen ligt vaak een oude pannenbedekking zonder isolatie."),
    ("malle", "Malle", "Antwerpen", "Voorkempen",
     "Oostmalle en Westmalle",
     "Malle bestaat uit Oostmalle en Westmalle. Beide kernen tellen veel vrijstaande woningen op ruime percelen met hoge bomen, wat de gootbelasting in de herfst verhoogt."),
    ("zoersel", "Zoersel", "Antwerpen", "Voorkempen",
     "Zoersel, Halle en Sint-Antonius",
     "Zoersel heeft drie kernen en veel groen. In de verkavelingen uit de jaren zeventig staan bungalows met flauw hellende daken, een dakvorm die gevoelig is voor inwaaiende regen onder de pannen."),
    ("putte", "Putte", "Antwerpen", "Zuiderkempen",
     "Putte, Beerzel, Grasheide en Peulis",
     "Putte ligt tussen Mechelen en Heist-op-den-Berg. De bebouwing bestaat uit dorpskernen met gesloten bebouwing en daarrond lintbebouwing langs de invalswegen."),
    ("lommel", "Lommel", "Limburg", "Noord-Limburg",
     "Lommel-Centrum, Kerkhoven, Kolonie, Barrier, Werkplaatsen en Heide",
     "Lommel is qua oppervlakte een van de grootste gemeenten van Limburg, met bebouwing verspreid over meerdere kernen op zandgrond. Veel woningen dateren uit de periode 1960 tot 1985."),
    ("pelt", "Pelt", "Limburg", "Noord-Limburg",
     "Overpelt, Neerpelt en Sint-Huibrechts-Lille",
     "Pelt ontstond in 2019 uit de fusie van Overpelt en Neerpelt. De gemeente heeft twee volwaardige kernen met daartussen lintbebouwing uit de jaren zestig en zeventig."),
    ("hamont-achel", "Hamont-Achel", "Limburg", "Noord-Limburg",
     "Hamont en Achel",
     "Hamont-Achel grenst aan Nederland. Hamont heeft een historische stadskern met gesloten bebouwing, Achel is landelijker met veel losse hoeves en bijgebouwen."),
    ("bocholt", "Bocholt", "Limburg", "Noord-Limburg",
     "Bocholt, Kaulille en Reppel",
     "Bocholt is een landelijke gemeente langs de Zuid-Willemsvaart. Naast woningen staan er veel landbouwloodsen met golfplaten, waarvan een deel nog asbesthoudend is."),
    ("peer", "Peer", "Limburg", "Noord-Limburg",
     "Peer, Wijchmaal, Grote-Brogel en Kleine-Brogel",
     "Peer bestaat uit vier kernen. De bebouwing is overwegend open, met vrijstaande woningen uit de jaren zeventig en tachtig waarvan de dakbedekking nu de vervangingsleeftijd nadert."),
    ("bree", "Bree", "Limburg", "Maasland",
     "Bree, Opitter, Tongerlo, Gerdingen en Beek",
     "Bree heeft een historische kern met beschermde panden en daarbuiten verkavelingen. Voor het beschermde stadsgezicht gelden aparte voorwaarden bij het wijzigen van dakvorm of dakbedekking."),
    ("kinrooi", "Kinrooi", "Limburg", "Maasland",
     "Kinrooi, Molenbeersel, Kessenich en Ophoven",
     "Kinrooi ligt aan de Maas, tegen de Nederlandse grens. De open ligging in het rivierdal betekent weinig beschutting tegen wind op de dakranden."),
    ("maaseik", "Maaseik", "Limburg", "Maasland",
     "Maaseik, Neeroeteren en Opoeteren",
     "Maaseik heeft een beschermde historische stadskern met leien en pannen op steile daken. In de buitenwijken en in Neeroeteren en Opoeteren overheerst naoorlogse open bebouwing."),
    ("dilsen-stokkem", "Dilsen-Stokkem", "Limburg", "Maasland",
     "Dilsen, Stokkem, Lanklaar, Rotem en Elen",
     "Dilsen-Stokkem bestaat uit vijf kernen langs de Maas. Stokkem heeft een oude stadskern, de overige kernen zijn landelijk met veel open bebouwing."),
]

BY_SLUG = {g[0]: g for g in GEMEENTEN}
